### ISSUE TITLE
Audio and Subtitle Dialog Selector Strings

### ISSUE THREAD

**Issue by atcronin** [MediaBrowser/Emby.Kodi#11]
Would it be possible to add 
' - Default ' and
' - Forced '
to the list of Audio and Subtitle Streams to help identify them
And eventually parse through the 'title' tag from the streams that typically holds the stream name.

Playbackutils.py

            elif 'Subtitle' in stream['Type']:
                try:
                    track = stream['Language']
                    if stream[u'IsDefault']:
                        track += " - Default"
                    if stream[u'IsForced']:
                        track += " - Forced"
                    subtitleStreamsList[track] = index
                    subtitleStreams.append(track)

**Comment by angelblue05** [comment]
I will review and let you know. It is indeed lacking details.

**Comment by atcronin** [comment]
using the language value as the index also causes issues returning the correct stream index.
If movie has multiple streams with same language eg. LOTR EE has 4 "eng" audio tracks and 6 "eng" subtitle streams.
I fixed that by changing
   track = stream['Language']
   to
   track = "Stream " + str(index) + ": " + stream['Language']

**Comment by angelblue05** [comment]
http://emby.media/community/index.php?/topic/19739-emby-for-kodi-beta/?p=252691
