### ISSUE TITLE
Improve 5.1 Audio Quality

### ISSUE THREAD

**Issue by atcronin** [MediaBrowser/Emby.Kodi#12]
AudioBitrate is not provided so 5.1 streams are transcoded to a 128k aac which sounds horrible.

A quick fix is to change the playurl in playutils.py

<code>playurl = "%s&VideoCodec=h264&<b>AudioCodec=ac3&AudioBitrate=384000&MaxAudioChannels=6</b>&deviceId=%s&VideoBitrate=%s" % (playurl, deviceId, self.getVideoBitRate()*1000)</code>

Option to set audio codec+bitrate+channels preference in settings would be good.

**Comment by atcronin** [comment]
Added code to detect channels and specifiy AudioBitrate based on number of channels. 

    def audioSubsPref(self, url, mediaSources):

        WINDOW = xbmcgui.Window(10000)
        # Present the list of audio to select from
        audioStreamsList = {}
        audioStreamsChannelsList = {}
        audioStreams = []
        selectAudioIndex = ""
        subtitleStreamsList = {}
        subtitleStreams = ['No subtitles']
        selectSubsIndex = ""
        playurlprefs = "%s" % url

        mediaStream = mediaSources[0].get('MediaStreams')
        for stream in mediaStream:
            index = stream['Index']
            # Since Emby returns all possible tracks together, have to sort them.
            if 'Audio' in stream['Type']:
                try:
                    track = stream['Language']
                    track += " " + str(stream[u'ChannelLayout'])
                    if stream[u'IsDefault']:
                        track += " - Default"

                    audioStreamsChannelsList[index] = stream[u'Channels']
                    audioStreamsList[track] = index
                    audioStreams.append(track)
                except:
                    track = stream['Codec']
                    audioStreamsList[track] = index
                    audioStreams.append(track)

            elif 'Subtitle' in stream['Type']:
                try:
                    track = stream['Language']
                    if stream[u'IsDefault']:
                        track += " - Default"

                    if stream[u'IsForced']:
                        track += " - Forced"

                    subtitleStreamsList[track] = index
                    subtitleStreams.append(track)
                except:
                    track = stream['Codec']
                    subtitleStreamsList[track] = index
                    subtitleStreams.append(track)

        if len(audioStreams) > 1:
            resp = xbmcgui.Dialog().select("Choose the audio stream", audioStreams)
            if resp > -1:
                # User selected audio
                selected = audioStreams[resp]
                selected_audioIndex = audioStreamsList[selected]
                playurlprefs += "&AudioStreamIndex=%s" % selected_audioIndex
                selectAudioIndex = str(selected_audioIndex)
            else: return False
        else: # There's only one audiotrack.
            audioIndex = audioStreamsList[audioStreams[0]]
            playurlprefs += "&AudioStreamIndex=%s" % audioIndex
            selectAudioIndex = str(audioIndex)

        if len(subtitleStreams) > 1:
            resp = xbmcgui.Dialog().select("Choose the subtitle stream", subtitleStreams)
            if resp == 0:
                # User selected no subtitles
                pass
            elif resp > -1:
                # User selected subtitles
                selected = subtitleStreams[resp]
                selected_subsIndex = subtitleStreamsList[selected]
                playurlprefs += "&SubtitleStreamIndex=%s" % selected_subsIndex
                selectSubsIndex = str(selected_subsIndex)
            else: return False

        #Specify AudioBitrate for stereo vs 5.1
        if len(audioStreamsChannelsList) > 0:
            AudioChannels = audioStreamsChannelsList[int(selectAudioIndex)]
            if AudioChannels > 2:
                playurlprefs += "&AudioBitrate=384000"
            else: playurlprefs += "&AudioBitrate=192000"

        # Reset the method with the new playurl
        WINDOW.setProperty("%splaymethod" % playurlprefs, "Transcode")
        WINDOW.setProperty("%sAudioStreamIndex" % playurlprefs, selectAudioIndex)
        WINDOW.setProperty("%sSubtitleStreamIndex" % playurlprefs, selectSubsIndex)

        return playurlprefs

**Comment by angelblue05** [comment]
I will review and let you know for next version. Thanks!

**Comment by angelblue05** [comment]
@atcronin 
Is specifying the audiobitrate necessary? How did you come up with those values - 384000 and 192000?

**Comment by atcronin** [comment]
without specifying you get 128k regardless of number of channels.
I just went with 192 and 384 as those values provide adequate quality in ac3, and are standard values on dvd's etc.
I am using ac3 as my requested audio codec, as ffmpeg states it is of better quality than the inbuilt aac codec. plus you get the advantage of being able to bitstream 5.1 ac3 over spdif, for those that still use spdif.

**Comment by angelblue05** [comment]
http://emby.media/community/index.php?/topic/19739-emby-for-kodi-beta/?p=252691
