### ISSUE TITLE
Plugin no longer works after update to server. 

### ISSUE THREAD

**Issue by Tombert** [MediaBrowser/Emby.Kodi#13]
My server auto-updated to the latest Emby, and now whenever I try and play a video through Kodi, I get the popup saying "Opening Stream", but nothing happens.

**Comment by Tombert** [comment]
I'd like to note that the video streams fine from the web interface, and even through UPnP on Kodi, which indicates to me that the issue is with this plugin.

**Comment by angelblue05** [comment]
@Tombert 
Please post on our forums, and post your log thanks.
http://emby.media/community/index.php?/topic/17599-how-to-report-a-problem/
