### ISSUE TITLE
Not all Emby music albums are available on Kodi

### ISSUE THREAD

**Issue by Danita** [MediaBrowser/Emby.Kodi#16]
Fist of all, thanks a lot for Emby and for Emby for Kodi, they're awesome! :beers: 

I'm having a problem with music albums. In Emby I have 413 albums, I can see them from Emby.Web under Home > Music > Albums. But when I open the Music item in Kodi, only 176 appear and most of them have a different name than which they have on Emby.

I now see on the Emby.Kodi README that music is "unsupported", is that correct? Should I delete the Emby music addon and load the library as local?

Thanks!

**Comment by angelblue05** [comment]
:+1: 
Music is supported - I will update the section. For the albums not showing up, can you check the songs are showing up under the artist? If so, then you are having the singles issue which still needs to be fixed.

**Comment by Danita** [comment]
Thanks @angelblue05! I checked with one of the missing albums and if searched by artist it was there, so it seems I'm affected by the dreaded "Singles issue". I found the issue on the forums. Well, I'll have to wait! :smile: Thanks!

**Comment by angelblue05** [comment]
Not for too long, I've been working on the issue. :)

**Comment by Danita** [comment]
Yay! Thanks again for making this available for free!

**Comment by angelblue05** [comment]
This should be resolved in the latest beta version 1.1.53 if you want to try it out. Otherwise, the fix will eventually come to stable once things are stable in beta.

**Comment by Danita** [comment]
Wow, this is great news! How stable is the beta for everyday use? Might be considering switching!

**Comment by angelblue05** [comment]
It is pretty stable or as stable as it can be - you may get some occasional bugs at times, but you can always disable auto updating so you can control when you decide to update beta versions, if you are on a version that works well for you.

**Comment by Danita** [comment]
@angelblue05 It's working perfectly! Now it's time to clean up my library, thanks! :beers:

**Comment by angelblue05** [comment]
Awesome, thanks for letting me know :)
