### ISSUE TITLE
How to update addon?

### ISSUE THREAD

**Issue by Danita** [MediaBrowser/Emby.Kodi#17]
I'm trying to debug a problem with my music library (#16) and I wanted to make sure I have the last version of the addon. I checked on Kodi and it seems I have **1.1.39**.

Then I see on the [forums](http://emby.media/community/index.php?/topic/19739-emby-for-kodi-beta/page-13) the last version is **1.1.52**, but then I come back to this repository and I see the latest release is **1.1.48**.

Which one is OK? I thought Kodi had auto update for addons? How do I update to the latest version?

**Comment by angelblue05** [comment]
1.1.39 is the stable version of the add-on. 1.1.52 is the latest beta version - to have this version, you need to install our beta repository. If you have the beta repository installed and it's stuck displaying 1.1.48, then try to force check for an update in Kodi (in Isengard, the option is located in the side blade)

**Comment by Danita** [comment]
Thanks, @angelblue05! That cleared up the confusion. I'll stay on stable for now then :smile:
