### ISSUE TITLE
[next-gen] Missing HDR type in video database

### ISSUE THREAD

**Issue by TehTux** [MediaBrowser/Emby.Kodi#464]
Can you please use the HDR field (strHdrType https://kodi.wiki/view/Databases/MyVideos) in the video database (https://github.com/MediaBrowser/plugin.video.emby/blob/next-gen/database/video_db.py) so that the media flags are displayed in Kodi? Thanks a lot!

**Comment by quickmic** [comment]
Seems to be new for Kodi 20. I'll check that.

**Comment by quickmic** [comment]
HDR flags added
