### ISSUE TITLE
Live TV doesn't populate Simple IPTV Client

### ISSUE THREAD

**Issue by northernpowerhouse** [MediaBrowser/Emby.Kodi#465]
I'm on Kodi Nexus, Emby Server 4.8.0.21, and on add-on version 7.x and 8.1 the plug in does not populate the PVR, even with Simple IPTV Client (latest) installed, after syncing Live TV (which shows me all my emby live TV channels in the popup notification while its syncing.

No difference after reinstalling Kodi from scratch.

**Comment by northernpowerhouse** [comment]
I'm using addon mode, by the way, Movies and TV Shows work fine, showing in my library and in the video addon

**Comment by quickmic** [comment]
Can you please try the 8.X version.
https://kodi.emby.tv/Public%20testing/plugin.video.emby-next-gen-8.0.4.zip
If the issue still appears, let me know and send me a kodi.log after LiveTV sync for review.

**Comment by quickmic** [comment]
Closed due to no feedback.
