### ISSUE TITLE
Possible memory leak on TvShow and Music Sync

### ISSUE THREAD

**Issue by AdamN1** [MediaBrowser/Emby.Kodi#482]
Recently I done full sync of emby DB on machine with 1GB RAM and doing sync kodi was killed by OOM.
Clean kodi use only 300MB with rest of the system it consume like 630MB living 300MB free i think it's enough memory.

I have second machine with 2GB RAM and sometime it also crash doing full sync.

OOM situation happens only in the TvSHow and Music database Movies works fine.

What kind of logs can helps to trace this memory leaks?

**Comment by quickmic** [comment]
Which version and how many items (episodes) you try to sync via tvshows?
Also lower the paging factor in plugin settings (expert mode) -> plugin config menu -> Sync -> Paging - items requested

**Comment by quickmic** [comment]
no response, closed.
