### ISSUE TITLE
Create new release version for emby 4.8.x compatibility

### ISSUE THREAD

**Issue by moetayuko** [MediaBrowser/Emby.Kodi#493]
Emby 4.8.x has become the release version, but the latest plugin release 8.2.14 is incompatible. Using a beta plugin with a release emby doesn't sound good to me, please create a release version of the plugin for use with emby 4.8.x

**Comment by moetayuko** [comment]
btw 8.2.15 works with Emby 4.8.x, 9.4.9 doesn't

**Comment by quickmic** [comment]
9.X will be the next stable release. If you have issues with 9.X please upload logs for review.
https://emby.media/community/index.php?/topic/123707-embyforkodi-next-gen-9xx-support/
