### ISSUE TITLE
Report playback progress on manual changes

### ISSUE THREAD

**Issue by LukePulverenti** [MediaBrowser/Emby.Kodi#6]
It looks like you have a 3 second progress interval, which is fine. When a manual change is made - e.g., pause, unpause, seek, volume change, etc, then do an  extra report right after that manual change.

By manual change I mean either a change in the UI by the user, or a command coming through the api.

For reference, see:

http://emby.media/community/index.php?/topic/2344-android-mobile/?p=223183

Thanks.

**Comment by angelblue05** [comment]
Report already works this way. However, there is this issue that no command will be accepted during the first minute of playback. After, everything is fine.

**Comment by angelblue05** [comment]
This will be fix shortly.... Already fixed in the cleanup branch.

**Comment by angelblue05** [comment]
Fixed in version 1.1.15
