### ISSUE TITLE
Sync playing up in new builds

### ISSUE THREAD

**Issue by Saner2oo2** [MediaBrowser/Emby.Kodi#8]
Hiya,

I get no movies at all in all builds in the lastest beta, TV shows the shows, but no episodes

This happens with Kodi 15 final, and 16a1 (i just updatex to 16 this morning)

I tried a manual sync and that just does the same.

One debug log.

https://drive.google.com/file/d/0B0msdgxYghdPdGNLek14RTViN0k/view?usp=docslist_api

(Tooo large for pastebin or xbmclogs)
 Thanks in advance

**Comment by Saner2oo2** [comment]
ok it now syncs fine, but wont play

http://sprunge.us/BOST

**Comment by angelblue05** [comment]
@Saner2oo2 
If you opened a post in our forums, we could have helped you sooner. Sorry that it took so long to respond. Anyway, it seems like Kodi doesn't like your path or is unable to access them. You are using a nfs share?

```python
13:32:27 5978.656738 T:1738888256  NOTICE: EMBY PlayUtils -> logMsg : Can't verify path (assumed NFS). Still try direct play.
13:32:27 5978.661133 T:1738888256  NOTICE: EMBY PlayUtils -> logMsg : File is direct playing.
13:32:27 5978.671387 T:1738888256  NOTICE: plugin.video.emby stopped
13:32:27 5978.734863 T:1968082944  NOTICE: DVDPlayer: Opening: /media/3TB/Movies/media/usbhd-sdd3/xbmc/Movies/Before I Go to Sleep (2014)/Before I Go to Sleep.mkv
13:32:27 5978.735352 T:1968082944 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
13:32:27 5978.735840 T:1794110528  NOTICE: Thread DVDPlayer start, auto delete: false
13:32:27 5978.736328 T:1794110528  NOTICE: Creating InputStream
13:32:27 5978.736816 T:1794110528   ERROR: CDVDPlayer::OpenInputStream - error opening [/media/3TB/Movies/media/usbhd-sdd3/xbmc/Movies/Before I Go to Sleep (2014)/Before I Go to Sleep.mkv]
