### ISSUE TITLE
Howto req: migrate from mysql setup to Emby.Kodi + list of benefits/downsides

### ISSUE THREAD

**Issue by piejanssens** [MediaBrowser/Emby.Kodi#9]
I'm using a MySQL server to sync the video db across my devices.
I am interested in moving to Emby.Kodi so that I can stream PVR when I'm not home.

- What is the best way to migrate my db?
- What are the downsides?
- Can I still use Kodi's PVR features or do I have to use a third party app to watch PVR streams from Emby?

**Comment by xnappo** [comment]
Best to have this discussion in our forums:
http://emby.media/community/index.php?/forum/99-kodi/

But briefly:

1. First set up the Emby server.  Make sure that all your metadata and watched statuses are correct
2. Take your MySQL offline / back it up / move it
3. Remove any video/music sources, delete video and music DB.
4. Install the Emby addon

There are no downsides other than it still being in development :)

Yes, you can still use Kodi's PVR features, depending on the backend you might look into Emby's ability to supplement them.
